//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Entity_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int Id { get; set; }
        public string Month { get; set; }
        public Nullable<int> Home_rent { get; set; }
        public Nullable<int> Water_bill { get; set; }
        public Nullable<int> Dirty_bill { get; set; }
        public Nullable<int> Service_charge { get; set; }
        public Nullable<int> Gass_bill { get; set; }
        public Nullable<int> Other_bill { get; set; }
        public Nullable<int> Previous_bill { get; set; }
        public Nullable<int> Total_bill { get; set; }
        public Nullable<int> Submission { get; set; }
        public Nullable<int> Rest_of_bill { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int Tanat_id { get; set; }
    
        public virtual Tanant Tanant { get; set; }
    }
}
