//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Entity_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner
    {
        public Owner()
        {
            this.Caretakers = new HashSet<Caretaker>();
            this.Costs = new HashSet<Cost>();
            this.Tanants = new HashSet<Tanant>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Nid { get; set; }
        public int Mobile { get; set; }
        public int House_no { get; set; }
        public string Road_no { get; set; }
        public string Jala { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Picture { get; set; }
    
        public virtual ICollection<Caretaker> Caretakers { get; set; }
        public virtual ICollection<Cost> Costs { get; set; }
        public virtual ICollection<Tanant> Tanants { get; set; }
    }
}
