//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Entity_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tanant
    {
        public Tanant()
        {
            this.Bills = new HashSet<Bill>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Father_name { get; set; }
        public string Mother_name { get; set; }
        public string Company_name { get; set; }
        public Nullable<int> Nid_number { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Starting_month { get; set; }
        public string Nid_pic { get; set; }
        public string Picture { get; set; }
        public int Care_id { get; set; }
        public int Owner_id { get; set; }
    
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual Caretaker Caretaker { get; set; }
        public virtual Owner Owner { get; set; }
    }
}
